# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  persistCredentials: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'SQLiteBrowser/*.csproj'
    feedsToUse: 'select'
# increment version to be completed, having trouble with git
#- task: PowerShell@2
#  inputs:
#    filePath: versionIncrement.ps1

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: 'SQLiteBrowser/*.csproj'
    configuration: 'release'
    restoreNugetPackages: true



- task: PublishPipelineArtifact@0
  inputs:
    artifactName: artifacts

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '78682d02-a4cd-4574-ac0a-625cd1f6cd8c/2b60df49-c3d6-42c9-b110-19c2857331ed'
    allowPackageConflicts: true
